name: bigbang
channels:
  - defaults
dependencies:
  - python=3.7
  - ipykernel
  - nb_conda_kernels
  - cython
  - beautifulsoup4>=4.9.3
  - coverage>=5.3.1
  - matplotlib>=3.3.3
  - graphviz
  - networkx>=2.5
  - pytz>=2020.5
  - Jinja2<3.1
  - jupyter
  - notebook
  - pandas>=1.2.1
  - pydot
  - pytest>=6.2.1
  - python-dateutil
  - pip
  - seaborn
  - scipy>=1.6.0
  - requests>=2.25.1
  - pyyaml
  - scikit-learn>=0.24.1
  - nltk
  - testfixtures
  - sphinx_rtd_theme

